name: Deploy Dispatch

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enviroment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - rc
        - prod

jobs:
    DeployTo:
        runs-on: ubuntu-latest
        steps:
        
        - name: Define vars
          run: |
            
            
            case ${{ inputs.environment }} in
              dev)
                URL_DEPLOY="udev"
                S3_FOLDER="dev"
              ;;
              rc)
                URL_DEPLOY="urc"
                S3_FOLDER="rc"
              ;;
              prod)
                URL_DEPLOY="uprod"
                S3_FOLDER="prod"
              ;;
            esac
            echo URL_DEPLOY >> $GITHUB_ENV
            echo S3_FOLDER >> $GITHUB_ENV
          
        - name: Print ref
          id: step_ONE
          run: |
            echo "REFF: ${{ github.ref }}"
            echo "S3: ${{ env.S3_FOLDER }}"
            echo "URL: ${{ env.S3_FOLDER }}"
