name: Deploy Dispatch

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enviroment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - rc
        - prod

jobs:
    DeployTo:
        runs-on: ubuntu-latest
        steps:
        
        - name: Define vars
          run: |
            case ${{ inputs.environment }} in
              dev) URL_DEPLOY="URL_DEPLOY=https://deploy.dev.hooks.yggs.io/"; S3_BUCKET="S3_BUCKET=dev-yggs-config"; S3_FOLDER="S3_FOLDER=Builds/" ;;
              rc) URL_DEPLOY="URL_DEPLOY=https://deploy.rc.hooks.yggs.io/"; S3_BUCKET="S3_BUCKET=yggs-config"; S3_FOLDER="S3_FOLDER=rc/Builds/" ;;
              prod) URL_DEPLOY="URL_DEPLOY=https://deploy.prod.hooks.yggs.io/"; S3_BUCKET="S3_BUCKET=yggs-config"; S3_FOLDER="S3_FOLDER=prod/Builds/" ;;
            esac
            
            echo $URL_DEPLOY >> $GITHUB_ENV
            echo $S3_BUCKET >> $GITHUB_ENV
            echo $S3_FOLDER >> $GITHUB_ENV
          
        - name: Print ref
          id: step_ONE
          run: |
            echo "REFF: ${{ github.ref }}"
            echo "URL: ${{ env.URL_DEPLOY }}"
            echo "BUCKET: ${{ env.S3_BUCKET }}"
            echo "FOLDER: ${{ env.S3_FOLDER }}"
