name: Deploy Dispatch

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enviroment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - rc
        - prod

jobs:
    DeployTo:
        runs-on: ubuntu-latest
        steps:
        
        - name: Define vars
          run: |
            case ${{ inputs.environment }} in
              dev)
                URL="udev"
                S3="dev"
              ;;
              rc)
                URL="urc"
                S3="rc"
              ;;
              prod)
                URL="uprod"
                S3="prod"
              ;;
            esac
            echo "URL_DEPLOY=URL" >> $GITHUB_ENV
            echo "S3_FOLDER=S3" >> $GITHUB_ENV
          
        - name: Print ref
          id: step_ONE
          run: |
            echo "REFF: ${{ github.ref }}"
            echo "S3: ${{ env.S3_FOLDER }}"
            echo "URL: ${{ env.S3_FOLDER }}"
