name: Deploy Dispatch

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enviroment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - rc
        - prod

jobs:
    DeployTo:
        runs-on: ubuntu-latest
        steps:
        
        - name: Define vars
          run: |
            case ${{ inputs.environment }} in
              dev) URL="https://deploy.dev.hooks.yggs.io/"; BUCKET="dev-yggs-config"; PATH="Builds/";;
              rc) URL="https://deploy.rc.hooks.yggs.io/"; BUCKET="yggs-config"; PATH="rc/Builds/";;
              prod) URL="https://deploy.prod.hooks.yggs.io/"; BUCKET="yggs-config"; PATH="prod/Builds/";;
            esac
            echo "URL_DEPLOY=URL" >> $GITHUB_ENV
            echo "S3_BUCKET=BUCKET" >> $GITHUB_ENV
            echo "S3_FOLDER=PATH" >> $GITHUB_ENV
          
        - name: Print ref
          id: step_ONE
          run: |
            echo "REFF: ${{ github.URL_DEPLOY }}"
            echo "URL: ${{ env.S3_BUCKET }}"
            echo "S3: ${{ env.S3_FOLDER }}"
