name: Deploy Dispatch

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Enviroment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - rc
        - prod

jobs:
    DeployTo:
        runs-on: ubuntu-latest
        steps:
        
        - name: Define vars
          run: |
            case ${{ inputs.environment }} in
            dev)
            echo "S3_FOLDER=https://deploy.dev.hooks.yggs.io/" >> $GITHUB_ENV
            ;;
            rc)
            echo "S3_FOLDER=https://deploy.rc.hooks.yggs.io/" >> $GITHUB_ENV
            ;;
            prod)
            echo "S3_FOLDER=https://deploy.prod.hooks.yggs.io/" >> $GITHUB_ENV
            ;;
            esac
          
        - name: Print ref
          id: step_ONE
          run: |
            echo "REFF: ${{ github.ref }}"
            echo "BASE REFF ${{ env.S3_FOLDER }}"
