name: Deploy Dispatch

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Deploy description'
        required: true
        type: string

jobs:
    DeployTo:
        runs-on: ubuntu-latest
        steps:
        - name: Dump GitHub context
          id: github_context_step
          run: echo '${{ toJSON(github) }}'
          
        - name: Print ref
          id: step_ONE
          run: |
            echo "REFF: ${{ github.ref }}"  
